user/models.py
from application import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(80))
    telephone = db.Column(db.BigInteger())
    email = db.Column(db.String(120))
    password = db.Column(db.String(128))
    college_name = db.Column(db.String(80))
    college_direction = db.Column(db.String(120))
    college_nit = db.Column(db.Integer())
    

    def __init__(self, full_name, telephone, email, password, college_name, college_direction, college_nit):
        self.full_name = full_name
        self.telephone = telephone
        self.email = email
        self.password = password
        self.college_name = college_name
        self.college_direction = college_direction
        self.college_nit = college_nit
    
    def __repr__(self):
        return '<User %r>' %self.full_name

user/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField, ValidationError, IntegerField
from wtforms.fields.html5 import EmailField
from werkzeug.security import check_password_hash

from user.models import User


class LoginForm(FlaskForm):

    college_nit = IntegerField('Nit del Colegio', [validators.InputRequired()])
    email = EmailField('Correo Electronico', [validators.InputRequired(), validators.Email()])
    password =PasswordField('Contraseña', [
        validators.Required(),
        validators.Length(min=4, max=80)
    ])

    def validate(self):
        rv=FlaskForm.validate(self)
        if not rv:
            return False
        
        user = User.query.filter_by(
            email = self.email.data, college_nit = self.college_nit.data
        ).first()

        if user:
            if not check_password_hash(user.password, self.password.data):
                self.password.errors.append('Incorrect email or password')
                return False
            return True
        else:
            self.password.errors.append('Incorrect email or password')
            return False

class RegisterForm(FlaskForm):

    full_name = StringField('Nombre Completo', [validators.InputRequired()], render_kw={"placeholder": "Alberto tovar"})
    telephone = IntegerField('Telefono', [validators.InputRequired(), validators.NumberRange(min=3000000000)],  render_kw={"placeholder": "365478"})
    email = EmailField('Correo Electronico', [validators.InputRequired(), validators.Email()],  render_kw={"placeholder": "myemail@example.com"})
    password = PasswordField('Nueva contraseña',[validators.InputRequired(),validators.Length(min=4, max=80)],  render_kw={"placeholder": "Contraseña"})
    confirm = PasswordField('Repetir contraseña', [validators.EqualTo('password', message='Passwords must match'),],  render_kw={"placeholder": "Repita contraseña"})
    college_name = StringField('Nombre del Colegio', [validators.InputRequired()],  render_kw={"placeholder": "Colegio alberto"})
    college_direction = StringField('Dirección del Colegio', [validators.InputRequired()],  render_kw={"placeholder": "Cra 1122 # 15-65"})
    college_nit = IntegerField('Nit', [validators.InputRequired()], render_kw={"placeholder": "123456789"})

    def validate_email(self,email):
        user = User.query.filter_by(email=email.data, college_nit=self.college_nit.data).first()
        if user is not None:
            raise ValidationError('El email y el nit ya esta en uso, porfavor utilice otro.')

class RecoveryForm(FlaskForm):

    college_nit = IntegerField('Nit', [validators.InputRequired()])
    email = EmailField('Correo Electronico', [validators.InputRequired(), validators.Email()])

class PasswordForm(FlaskForm):

    password = PasswordField('Nueva contraseña', [validators.InputRequired(), validators.Length(min=4, max=80)], render_kw={"placeholder": "Nueva contraseña"})
    confirm = PasswordField('Repetir contraseña', [validators.EqualTo('password', message='Passwords must match'),], render_kw={"placeholder": "Repita la contraseña"})

user/views.py
from flask import Blueprint,render_template, redirect, session, url_for, flash, Flask,abort
from flask_mail import Mail,Message
from werkzeug.security import generate_password_hash
from itsdangerous import URLSafeTimedSerializer
import random
import os


from user.models import User
from user.forms  import RegisterForm, LoginForm, RecoveryForm, PasswordForm
from application import db
from settings import mail_settings, MAIL_USERNAME,SECRET_KEY

#Create blueprint
user_app = Blueprint('user_app', __name__)
# Mail settings
app = Flask(__name__)
app.config.update(mail_settings)
mail = Mail(app)

ts = URLSafeTimedSerializer(secret_key=SECRET_KEY, salt = 'recover-key')

@user_app.route('/send_email')
def send_email(subject,recipients,body):
     with app.app_context():
            msg = Message(subject=subject,
                    sender=MAIL_USERNAME,
                    recipients=recipients, 
                    body=body)
            mail.send(msg)

@user_app.route('/register', methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        
        hashed_password = generate_password_hash(form.password.data)
        user = User(
            form.full_name.data,
            form.telephone.data,
            form.email.data,
            hashed_password,
            form.college_name.data,
            form.college_direction.data,
            form.college_nit.data
        )
        db.session.add(user)
        db.session.commit()
        send_email(subject="Registro exitoso As Contable!!",
                    recipients=[form.email.data], 
                    body="Bienvenido a As contable, su aliado en contabilidades de entidades")
        flash('Usted ya se encuentra registrado, porfavor inicie sesión')

        return redirect(url_for('.login'))
    return render_template('user/register.html', form=form, cache_id=random.randrange(10000))

@user_app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data, college_nit = form.college_nit.data).first()
        session['id'] = user.id
        print(session['id'])
        session['full_name'] = user.full_name

        return redirect(url_for('home_app.index'))
    
    return render_template('user/login.html', form=form, error=error, cache_id=random.randrange(10000))

@user_app.route('/logout')
def logout():
    session.pop('id')
    session.pop('full_name')
    flash('User logged out')
    return redirect(url_for('home_app.index'))

@user_app.route('/recovery', methods = ['GET', 'POST'])
def recovery():
    form = RecoveryForm()
    
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data, college_nit=form.college_nit.data).first()

        token = ts.dumps([form.email.data, form.college_nit.data], salt ='recover-key')
        recovery_url = url_for('.recover',token=token,_external=True)
        send_email(subject = "Password reset requested", recipients=[form.email.data], body=recovery_url)
        flash('Se envio un link a su correo, porfavor revise')
    
    return render_template('user/recovery.html', form=form)

@user_app.route('/recover/<token>', methods=[ 'GET', 'POST'])
def recover(token):
    try:
        [email,college_nit] = ts.loads(token, salt = 'recover-key', max_age=86400)
        print(email)
        print(college_nit)
    except:
        abort(404)
    
    form = PasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=email, college_nit=college_nit).first()
        hashed_password = generate_password_hash(form.password.data)
        user.password = hashed_password

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.login'))
    return render_template('user/recover.html', form=form, token=token)    

templates/user/login.html
{% extends "base.html" %} 

{% block title %}User Login{% endblock %} 
{% block link %}<link rel="stylesheet" href="{{ url_for('static', filename='loginstyle.css') }}?{{ cache_id }}">{% endblock %}
{% block content %}

<div class="row">

    <div class="offset-md-1 col-md-8 py-3" id="form">

        {% include '_flashmessages.html' %}
        <h4 class="text-center">Iniciar sesión en As Connect</h4>

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.login') }}" role="form">

            {{ form.hidden_tag() }}
            
            {{ render_field(form.college_nit, class='form-control') }}    
            {{ render_field(form.email, class='form-control') }}
            {{ render_field(form.password, class='form-control') }}

            <button type="submit" class="btn btn-primary my-3" >Iniciar sesión</button>
            <a type="button" class="btn btn-link mx-5" href="/recovery">¿Has olvidado tu contraseña?</a>
        </form>
    </div>
</div>
{% endblock %}

templates/user/recover.html
{% extends "base.html" %}

{% block title %}Asignar Contraseña{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-1 col-md-8 py-3" >
        {% include '_flashmessages.html' %}
        <h4 class="text-center">Nueva Contraseña</h4>

        {% from "_formhelpers.html" import render_field %}
        <form  method ="POST" action=" {{url_for('.recover',token=token) }}">

            {{ form.hidden_tag()}}

            {{ render_field(form.password, class='form-control')}}
            {{ render_field(form.confirm, class='form-control')}}

            <button type="submit" class="btn btn-primary my-3">Enviar</button>

        </form>
    </div>
</div>

{% endblock %}

templates/user/recovery.html
{% extends "base.html" %}

{% block title %}Recuperar Contraseña{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-1 col-md-8 py-3" >
        {% include '_flashmessages.html' %}
        <h4 class="text-center">Recuperar Contraseña</h4>

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('.recovery') }}" role="form">

            {{ form.hidden_tag()}}

            {{ render_field(form.college_nit, class='form-control')}}
            {{ render_field(form.email, class='form-control')}}

            <button type="submit" class="btn btn-primary my-3">Enviar</button>

        </form>
    </div>
</div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}User Registration{% endblock %}
{% block link %}<link rel="stylesheet" href="{{ url_for('static', filename='registerstyle.css') }}?{{ cache_id }}">{% endblock %}

{% block content %}

<div class="row">

    <div class="offset-md-2 col-md-8 rounded px-4" id="form">

        <h4 class="text-center my-3">Registro de usuario</h4>

        {% from "_formhelpers.html" import render_field %}
        <form method="POST" action="{{ url_for('user_app.register')}}" role="form">
            {{ form.hidden_tag()  }}
            
            {{ render_field(form.full_name, class="form-control") }}
            {{ render_field(form.telephone, class="form-control") }}
            {{ render_field(form.email, class="form-control") }}
            {{ render_field(form.password, class="form-control")}}
            {{ render_field(form.confirm, class="form-control") }}
            {{ render_field(form.college_name, class="form-control") }}
            {{ render_field(form.college_direction, class="form-control") }}
            {{ render_field(form.college_nit, class="form-control") }}
            
            <button type="submit" class="btn btn-primary my-3">Register</button>
        </form>

    </div>
</div>

{% endblock %}